# Site
name: "journipod"
title: "journipod"
description: "A blog about Travel, Food and Reading"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 'UA-46278016-1'
#disqus: 'journipod'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

#Authors
authors:
  Sara:
   name: Sara
   display_name: Sara
   avatar: 'assets/images/avatar.png'
   #gravatar: e56154546cf4be74e393c62d1ae9f9d4
   email: journipod@gmail.com
   web: https://www.journipod.com
   twitter: https://twitter.com/journipod
   facebook: https://www.facebook.com/journipod
   #description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

Hu:
  name: Sara
  display_name: Sara    
  avatar: 'assets/images/avatar.png'
   # gravatar: b1cc14991db7a456fcd761680bbc8f81
  email: journipod@gmail.com
  web: https://www.journipod.com
  twitter: https://twitter.com/journipod
   # description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-9006173418797422"
# adsense-data-ad-slot: "8576359069"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
